In [3]:
from pandas_datareader import data, wb
import pandas as pd
import numpy as np
import scipy 
import statsmodels
import sklearn

In [ ]:
# http://pandas.pydata.org/pandas-docs/stable/remote_data.html

In [5]:
start = pd.to_datetime('2010-01-01')
end = pd.to_datetime('2016-06-01')
f = data.DataReader("F", 'yahoo', start, end)
f.head()

             Open   High    Low  Close     Volume  Adj Close
Date
2010-01-04  10.17  10.28  10.05  10.28   60855800   8.755953
2010-01-05  10.45  11.24  10.40  10.96  215620200   9.335141
2010-01-06  11.21  11.46  11.13  11.37  200070600   9.684357
2010-01-07  11.46  11.69  11.32  11.66  130201700   9.931363
2010-01-08  11.67  11.74  11.46  11.69  130463000   9.956916

In [6]:
aapl = data.Options('aapl', 'yahoo')
apple_data = aapl.get_all_data()
apple_data.head()

                                             Last   Bid    Ask  Chg  PctChg  \
Strike Expiry     Type Symbol
10.0   2016-06-17 call AAPL160617C00010000  82.95  81.8  82.90  0.0     0.0
                  put  AAPL160617P00010000   0.01   0.0   0.01  0.0     0.0
12.5   2016-06-17 call AAPL160617C00012500   0.00  88.5  88.95  0.0     0.0
                  put  AAPL160617P00012500   0.00   0.0   0.03  0.0     0.0
15.0   2016-06-17 call AAPL160617C00015000   0.00  86.0  86.45  0.0     0.0

                                            Vol  Open_Int      IV  Root  \
Strike Expiry     Type Symbol
10.0   2016-06-17 call AAPL160617C00010000   20         0  0.0000  AAPL
                  put  AAPL160617P00010000  100       100  3.6250  AAPL
12.5   2016-06-17 call AAPL160617C00012500    0         0  9.3438  AAPL
                  put  AAPL160617P00012500    0         0  3.5625  AAPL
15.0   2016-06-17 call AAPL160617C00015000    0         0  8.3740  AAPL

                                           IsNonstandard Underlying  \
Strike Expiry     Type Symbol
10.0   2016-06-17 call AAPL160617C00010000         False       AAPL
                  put  AAPL160617P00010000         False       AAPL
12.5   2016-06-17 call AAPL160617C00012500         False       AAPL
                  put  AAPL160617P00012500         False       AAPL
15.0   2016-06-17 call AAPL160617C00015000         False       AAPL

                                            Underlying_Price  \
Strike Expiry     Type Symbol
10.0   2016-06-17 call AAPL160617C00010000             97.72
                  put  AAPL160617P00010000             97.72
12.5   2016-06-17 call AAPL160617C00012500             97.72
                  put  AAPL160617P00012500             97.72
15.0   2016-06-17 call AAPL160617C00015000             97.72

                                                    Quote_Time
Strike Expiry     Type Symbol
10.0   2016-06-17 call AAPL160617C00010000 2016-06-02 16:00:00
                  put  AAPL160617P00010000 2016-06-02 16:00:00
12.5   2016-06-17 call AAPL160617C00012500 2016-06-02 16:00:00
                  put  AAPL160617P00012500 2016-06-02 16:00:00
15.0   2016-06-17 call AAPL160617C00015000 2016-06-02 16:00:00

In [8]:
gdp = data.DataReader("GDP", "fred", start, end)
gdp.head()

                GDP
DATE
2010-01-01  14681.1
2010-04-01  14888.6
2010-07-01  15057.7
2010-10-01  15230.2
2011-01-01  15238.4

In [16]:
ip = data.DataReader("5_Industry_Portfolios", "famafrench")
ip[0]

         Cnsmr  Manuf  HiTec  Hlth   Other
Date
2010-01  -1.95  -4.02  -7.59   0.00  -1.67
2010-02   3.90   3.23   4.34   0.37   3.38
2010-03   6.35   4.74   6.86   3.61   8.42
2010-04   1.52   3.31   2.45  -2.23   2.16
2010-05  -5.70  -8.88  -7.27  -8.01  -8.83
2010-06  -6.51  -5.19  -5.67  -1.63  -7.65
2010-07   6.44   8.48   7.97   2.15   7.48
2010-08  -3.35  -3.79  -5.49  -1.66  -7.51
2010-09   9.87   8.83  11.40   9.00   8.83
2010-10   3.61   4.33   5.96   2.01   2.58
2010-11   2.89   2.46  -1.07  -3.33   0.51
2010-12   4.12   7.27   6.16   5.41   9.70
2011-01  -1.28   4.25   3.08  -0.71   1.93
2011-02   2.91   4.88   3.38   3.33   2.66
2011-03   1.79   1.73  -0.85   2.29  -0.87
2011-04   4.31   2.47   3.16   6.37   1.10
2011-05   0.83  -2.59  -1.11   1.96  -2.39
2011-06  -0.93  -1.27  -2.15  -1.84  -2.05
2011-07  -1.38  -2.04  -1.36  -3.65  -3.72
2011-08  -2.91  -6.70  -6.53  -3.09  -7.59
2011-09  -5.14 -10.00  -5.08  -3.96 -10.30
2011-10   9.53  13.57  10.97   5.54  13.26
2011-11   0.44   1.45  -1.48   1.28  -1.59
2011-12   1.10  -0.08  -0.45   3.53   1.10
2012-01   3.41   3.10   6.88   3.38   6.77
2012-02   3.61   4.41   6.30   1.23   3.89
2012-03   4.07  -0.67   4.24   3.96   4.76
2012-04   0.24  -0.66  -1.26   0.61  -1.67
2012-05  -3.28  -7.78  -6.41  -3.28  -7.18
2012-06   2.01   3.23   3.81   6.80   4.76
...        ...    ...    ...    ...    ...
2013-07   5.10   5.44   5.44   7.89   5.30
2013-08  -3.86  -2.29  -0.80  -3.80  -3.66
2013-09   3.74   3.40   3.93   4.03   3.80
2013-10   4.52   4.44   4.28   3.83   3.75
2013-11   2.66   1.52   2.82   4.50   4.47
2013-12   1.12   2.83   4.06   0.64   3.06
2014-01  -5.95  -4.26  -1.79   1.64  -4.36
2014-02   4.92   5.13   4.69   6.48   3.43
2014-03   0.68   1.39  -0.68  -2.56   2.30
2014-04  -0.04   2.96  -0.88  -0.30  -1.55
2014-05   1.79   0.96   3.56   1.89   1.76
2014-06   1.55   3.00   2.69   2.86   2.08
2014-07  -3.26  -4.34   0.38  -0.33  -2.12
2014-08   5.33   3.97   3.39   5.44   4.42
2014-09  -1.70  -4.55  -1.42  -0.08  -1.02
2014-10   2.95   0.73   1.34   5.77   3.29
2014-11   6.27  -2.03   3.99   2.67   2.79
2014-12   0.09   0.36  -1.43  -0.88   1.06
2015-01  -0.76  -3.11  -3.62   1.56  -6.08
2015-02   5.58   3.83   8.34   4.32   6.83
2015-03  -0.47  -1.90  -2.42   0.86  -0.80
2015-04  -1.09   1.76   1.84  -1.38   0.48
2015-05   1.12  -1.15   1.68   4.89   1.67
2015-06  -0.92  -3.06  -2.83   0.08  -0.33
2015-07   4.18  -3.28   2.26   3.66   2.02
2015-08  -4.98  -4.77  -6.40  -8.37  -6.11
2015-09  -1.53  -3.95  -1.72  -7.27  -3.11
2015-10   5.43   8.72   9.88   7.74   6.57
2015-11   0.31  -0.09   0.54   0.71   1.18
2015-12   0.12  -4.68  -2.63   0.40  -2.63

[72 rows x 5 columns]